function noo_promisetest_PromiseTest(){var O='bootstrap',P='begin',Q='gwt.codesvr.noo.promisetest.PromiseTest=',R='gwt.codesvr=',S='noo.promisetest.PromiseTest',T='startup',U='DUMMY',V=0,W=1,X='iframe',Y='javascript:""',Z='position:absolute; width:0; height:0; border:none; left: -1000px;',$=' top: -1000px;',_='CSS1Compat',ab='<!doctype html>',bb='',cb='<html><head><\/head><body><\/body><\/html>',db='undefined',eb='DOMContentLoaded',fb=50,gb='Chrome',hb='eval("',ib='");',jb='script',kb='javascript',lb='moduleStartup',mb='moduleRequested',nb='noo_promisetest_PromiseTest',ob='Failed to load ',pb='head',qb='meta',rb='name',sb='noo.promisetest.PromiseTest::',tb='::',ub='gwt:property',vb='content',wb='=',xb='gwt:onPropertyErrorFn',yb='Bad handler "',zb='" for "gwt:onPropertyErrorFn"',Ab='gwt:onLoadErrorFn',Bb='" for "gwt:onLoadErrorFn"',Cb='#',Db='?',Eb='/',Fb='img',Gb='clear.cache.gif',Hb='baseUrl',Ib='noo.promisetest.PromiseTest.nocache.js',Jb='base',Kb='//',Lb='$noo.immediate',Mb='function',Nb='native',Ob='promise',Pb='postmessage',Qb=2,Rb='$noo.promise',Sb='emulated',Tb='selectingPermutation',Ub='noo.promisetest.PromiseTest.devmode.js',Vb='21647CAB6B77F5800D5B29C20F745EB0',Wb='410CF79CE277EC5575DCC36FD3436EBF',Xb='5B965436250B0B77FC3A9445C489FE5F',Yb='B4F3BC6B4BC44E5E9F276FC9D8B420F4',Zb='D41F8DC187D3FB935C44818B502FD547',$b='E0918A5F68FCB29680EE7D4A334FA857',_b=':',ac=10,bc='.cache.js',cc='loadExternalRefs',dc='end',ec='http:',fc='file:',gc='_gwt_dummy_',hc='__gwtDevModeHook:noo.promisetest.PromiseTest',ic='Ignoring non-whitelisted Dev Mode URL: ',jc=':moduleBase';var o=window;var p=document;r(O,P);function q(){var a=o.location.search;return a.indexOf(Q)!=-1||a.indexOf(R)!=-1}
function r(a,b){if(o.__gwtStatsEvent){o.__gwtStatsEvent({moduleName:S,sessionId:o.__gwtStatsSessionId,subSystem:T,evtGroup:a,millis:(new Date).getTime(),type:b})}}
noo_promisetest_PromiseTest.__sendStats=r;noo_promisetest_PromiseTest.__moduleName=S;noo_promisetest_PromiseTest.__errFn=null;noo_promisetest_PromiseTest.__moduleBase=U;noo_promisetest_PromiseTest.__softPermutationId=V;noo_promisetest_PromiseTest.__computePropValue=null;noo_promisetest_PromiseTest.__getPropMap=null;noo_promisetest_PromiseTest.__installRunAsyncCode=function(){};noo_promisetest_PromiseTest.__gwtStartLoadingFragment=function(){return null};noo_promisetest_PromiseTest.__gwt_isKnownPropertyValue=function(){return false};noo_promisetest_PromiseTest.__gwt_getMetaProperty=function(){return null};var s=null;var t=o.__gwt_activeModules=o.__gwt_activeModules||{};t[S]={moduleName:S};noo_promisetest_PromiseTest.__moduleStartupDone=function(e){var f=t[S].bindings;t[S].bindings=function(){var a=f?f():{};var b=e[noo_promisetest_PromiseTest.__softPermutationId];for(var c=V;c<b.length;c++){var d=b[c];a[d[V]]=d[W]}return a}};var u;function v(){w();return u}
function w(){if(u){return}var a=p.createElement(X);a.src=Y;a.id=S;a.style.cssText=Z+$;a.tabIndex=-1;p.body.appendChild(a);u=a.contentDocument;if(!u){u=a.contentWindow.document}u.open();var b=document.compatMode==_?ab:bb;u.write(b+cb);u.close()}
function A(k){function l(a){function b(){if(typeof p.readyState==db){return typeof p.body!=db&&p.body!=null}return /loaded|complete/.test(p.readyState)}
var c=b();if(c){a();return}function d(){if(!c){c=true;a();if(p.removeEventListener){p.removeEventListener(eb,d,false)}if(e){clearInterval(e)}}}
if(p.addEventListener){p.addEventListener(eb,d,false)}var e=setInterval(function(){if(b()){d()}},fb)}
function m(c){function d(a,b){a.removeChild(b)}
var e=v();var f=e.body;var g;if(navigator.userAgent.indexOf(gb)>-1&&window.JSON){var h=e.createDocumentFragment();h.appendChild(e.createTextNode(hb));for(var i=V;i<c.length;i++){var j=window.JSON.stringify(c[i]);h.appendChild(e.createTextNode(j.substring(W,j.length-W)))}h.appendChild(e.createTextNode(ib));g=e.createElement(jb);g.language=kb;g.appendChild(h);f.appendChild(g);d(f,g)}else{for(var i=V;i<c.length;i++){g=e.createElement(jb);g.language=kb;g.text=c[i];f.appendChild(g);d(f,g)}}}
noo_promisetest_PromiseTest.onScriptDownloaded=function(a){l(function(){m(a)})};r(lb,mb);var n=p.createElement(jb);n.src=k;if(noo_promisetest_PromiseTest.__errFn){n.onerror=function(){noo_promisetest_PromiseTest.__errFn(nb,new Error(ob+code))}}p.getElementsByTagName(pb)[V].appendChild(n)}
noo_promisetest_PromiseTest.__startLoadingFragment=function(a){return D(a)};noo_promisetest_PromiseTest.__installRunAsyncCode=function(a){var b=v();var c=b.body;var d=b.createElement(jb);d.language=kb;d.text=a;c.appendChild(d);c.removeChild(d)};function B(){var c={};var d;var e;var f=p.getElementsByTagName(qb);for(var g=V,h=f.length;g<h;++g){var i=f[g],j=i.getAttribute(rb),k;if(j){j=j.replace(sb,bb);if(j.indexOf(tb)>=V){continue}if(j==ub){k=i.getAttribute(vb);if(k){var l,m=k.indexOf(wb);if(m>=V){j=k.substring(V,m);l=k.substring(m+W)}else{j=k;l=bb}c[j]=l}}else if(j==xb){k=i.getAttribute(vb);if(k){try{d=eval(k)}catch(a){alert(yb+k+zb)}}}else if(j==Ab){k=i.getAttribute(vb);if(k){try{e=eval(k)}catch(a){alert(yb+k+Bb)}}}}}__gwt_getMetaProperty=function(a){var b=c[a];return b==null?null:b};s=d;noo_promisetest_PromiseTest.__errFn=e}
function C(){function e(a){var b=a.lastIndexOf(Cb);if(b==-1){b=a.length}var c=a.indexOf(Db);if(c==-1){c=a.length}var d=a.lastIndexOf(Eb,Math.min(c,b));return d>=V?a.substring(V,d+W):bb}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=p.createElement(Fb);b.src=a+Gb;a=e(b.src)}return a}
function g(){var a=__gwt_getMetaProperty(Hb);if(a!=null){return a}return bb}
function h(){var a=p.getElementsByTagName(jb);for(var b=V;b<a.length;++b){if(a[b].src.indexOf(Ib)!=-1){return e(a[b].src)}}return bb}
function i(){var a=p.getElementsByTagName(Jb);if(a.length>V){return a[a.length-W].href}return bb}
function j(){var a=p.location;return a.href==a.protocol+Kb+a.host+a.pathname+a.search+a.hash}
var k=g();if(k==bb){k=h()}if(k==bb){k=i()}if(k==bb&&j()){k=e(p.location.href)}k=f(k);return k}
function D(a){if(a.match(/^\//)){return a}if(a.match(/^[a-zA-Z]+:\/\//)){return a}return noo_promisetest_PromiseTest.__moduleBase+a}
function F(){var f=[];var g=V;function h(a,b){var c=f;for(var d=V,e=a.length-W;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
var i=[];var j=[];function k(a){var b=j[a](),c=i[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(s){s(a,d,b)}throw null}
j[Lb]=function(){{if(Mb==typeof window.setImmediate&&/{\s*\[native\scode\]\s*}/m.test(window.setImmediate.toString())){return Nb}else if(Mb==typeof window.Promise){return Ob}return Pb}};i[Lb]={'native':V,postmessage:W,promise:Qb};j[Rb]=function(){{if(Mb==typeof window.Promise){return Nb}return Sb}};i[Rb]={emulated:V,'native':W};__gwt_isKnownPropertyValue=function(a,b){return b in i[a]};noo_promisetest_PromiseTest.__getPropMap=function(){var a={};for(var b in i){if(i.hasOwnProperty(b)){a[b]=k(b)}}return a};noo_promisetest_PromiseTest.__computePropValue=k;o.__gwt_activeModules[S].bindings=noo_promisetest_PromiseTest.__getPropMap;r(O,Tb);if(q()){return D(Ub)}var l;try{h([Pb,Sb],Vb);h([Ob,Nb],Wb);h([Ob,Sb],Xb);h([Pb,Nb],Yb);h([Nb,Sb],Zb);h([Nb,Nb],$b);l=f[k(Lb)][k(Rb)];var m=l.indexOf(_b);if(m!=-1){g=parseInt(l.substring(m+W),ac);l=l.substring(V,m)}}catch(a){}noo_promisetest_PromiseTest.__softPermutationId=g;return D(l+bc)}
function G(){if(!o.__gwt_stylesLoaded){o.__gwt_stylesLoaded={}}r(cc,P);r(cc,dc)}
B();noo_promisetest_PromiseTest.__moduleBase=C();t[S].moduleBase=noo_promisetest_PromiseTest.__moduleBase;var H=F();if(o){var I=!!(o.location.protocol==ec||o.location.protocol==fc);o.__gwt_activeModules[S].canRedirect=I;function J(){var b=gc;try{o.sessionStorage.setItem(b,b);o.sessionStorage.removeItem(b);return true}catch(a){return false}}
if(I&&J()){var K=hc;var L=o.sessionStorage[K];if(!/^http:\/\/(localhost|127\.0\.0\.1)(:\d+)?\/.*$/.test(L)){if(L&&(window.console&&console.log)){console.log(ic+L)}L=bb}if(L&&!o[K]){o[K]=true;o[K+jc]=C();var M=p.createElement(jb);M.src=L;var N=p.getElementsByTagName(pb)[V];N.insertBefore(M,N.firstElementChild||N.children[V]);return false}}}G();r(O,dc);A(H);return true}
noo_promisetest_PromiseTest.succeeded=noo_promisetest_PromiseTest();