function noo_promisetest_PromiseTest(){var O='bootstrap',P='begin',Q='gwt.codesvr.noo.promisetest.PromiseTest=',R='gwt.codesvr=',S='noo.promisetest.PromiseTest',T='startup',U='DUMMY',V=0,W=1,X='iframe',Y='javascript:""',Z='position:absolute; width:0; height:0; border:none; left: -1000px;',$=' top: -1000px;',_='CSS1Compat',ab='<!doctype html>',bb='',cb='<html><head><\/head><body><\/body><\/html>',db='undefined',eb='DOMContentLoaded',fb=50,gb='Chrome',hb='eval("',ib='");',jb='script',kb='javascript',lb='moduleStartup',mb='moduleRequested',nb='noo_promisetest_PromiseTest',ob='Failed to load ',pb='head',qb='meta',rb='name',sb='noo.promisetest.PromiseTest::',tb='::',ub='gwt:property',vb='content',wb='=',xb='gwt:onPropertyErrorFn',yb='Bad handler "',zb='" for "gwt:onPropertyErrorFn"',Ab='gwt:onLoadErrorFn',Bb='" for "gwt:onLoadErrorFn"',Cb='#',Db='?',Eb='/',Fb='img',Gb='clear.cache.gif',Hb='baseUrl',Ib='noo.promisetest.PromiseTest.nocache.js',Jb='base',Kb='//',Lb='$noo.immediate',Mb='function',Nb='native',Ob='promise',Pb='postmessage',Qb=2,Rb='$noo.promise',Sb='emulated',Tb='user.agent',Ub='webkit',Vb='safari',Wb='msie',Xb=10,Yb=11,Zb='ie10',$b=9,_b='ie9',ac=8,bc='ie8',cc='gecko',dc='gecko1_8',ec=3,fc=4,gc='selectingPermutation',hc='noo.promisetest.PromiseTest.devmode.js',ic='0318531DA56AC6D59400B247377800CE',jc='0B944C5330721B9B412C45380E83223C',kc='0C31553BF2BE81BDA2F1ABEDC8277BBE',lc='13737E2A0E9905111105B5C3DC66E8B1',mc='25159F97A5938CB1F1DBBD189C58476C',nc='2A8D099CB8775697E0555D33202E81F0',oc='30E36F9D1E4D3BE8C23F25EEC7EF0E52',pc='3949B24EC4D84DF9FAC1EEFDCA3112CA',qc='41D2C806CD445D38928940CFD1DC27A7',rc='4D08CC48CE56E9628899539831B5274B',sc='6983570BF48F125A92BAA3633260A0DC',tc='7876B61CC6F40438547DF054E6F1BFCF',uc='819B41EAE08D63FB33809C85A7093A93',vc='9B7508B26AE34CBAEDF094797A515767',wc='A1D66949E68D90CF2500FA4B79C8D7FF',xc='A5A72060ABF0B9EC0CCA2C0C2877FA0E',yc='A675C65899CA248CF47E735E7597878B',zc='A9C334D8DE19005A7DDAD966F3C2C0AD',Ac='B6DE4A513F01904CB852C8491EB36A9F',Bc='C00E77BB65AA3D3065CA27CDB0F0C6A4',Cc='D7B97E598F3B2F8EB79C27914A7F84FC',Dc='DB5BFD1762B17D02BED838CA2F67E58C',Ec='DC7AE322FAEBEFA7FF398EDC6C34F56A',Fc='DDF16519475D1F1DD72A1F75C6CE0B28',Gc='DE845993C59EE66C5478F28779AAA30B',Hc='E4A15121B50A3391251946E1C309BFAC',Ic='E78F4266012DA62DF0585ACC6F4DEC97',Jc='F88C4B881927B1DE680C6C886C735CC1',Kc='FDB0A974904E9CCA502D0A4D418BB458',Lc='FE6DE9A86EBF955CBA56BFC834C3C578',Mc=':',Nc='.cache.js',Oc='loadExternalRefs',Pc='end',Qc='http:',Rc='file:',Sc='_gwt_dummy_',Tc='__gwtDevModeHook:noo.promisetest.PromiseTest',Uc='Ignoring non-whitelisted Dev Mode URL: ',Vc=':moduleBase';var o=window;var p=document;r(O,P);function q(){var a=o.location.search;return a.indexOf(Q)!=-1||a.indexOf(R)!=-1}
function r(a,b){if(o.__gwtStatsEvent){o.__gwtStatsEvent({moduleName:S,sessionId:o.__gwtStatsSessionId,subSystem:T,evtGroup:a,millis:(new Date).getTime(),type:b})}}
noo_promisetest_PromiseTest.__sendStats=r;noo_promisetest_PromiseTest.__moduleName=S;noo_promisetest_PromiseTest.__errFn=null;noo_promisetest_PromiseTest.__moduleBase=U;noo_promisetest_PromiseTest.__softPermutationId=V;noo_promisetest_PromiseTest.__computePropValue=null;noo_promisetest_PromiseTest.__getPropMap=null;noo_promisetest_PromiseTest.__installRunAsyncCode=function(){};noo_promisetest_PromiseTest.__gwtStartLoadingFragment=function(){return null};noo_promisetest_PromiseTest.__gwt_isKnownPropertyValue=function(){return false};noo_promisetest_PromiseTest.__gwt_getMetaProperty=function(){return null};var s=null;var t=o.__gwt_activeModules=o.__gwt_activeModules||{};t[S]={moduleName:S};noo_promisetest_PromiseTest.__moduleStartupDone=function(e){var f=t[S].bindings;t[S].bindings=function(){var a=f?f():{};var b=e[noo_promisetest_PromiseTest.__softPermutationId];for(var c=V;c<b.length;c++){var d=b[c];a[d[V]]=d[W]}return a}};var u;function v(){w();return u}
function w(){if(u){return}var a=p.createElement(X);a.src=Y;a.id=S;a.style.cssText=Z+$;a.tabIndex=-1;p.body.appendChild(a);u=a.contentDocument;if(!u){u=a.contentWindow.document}u.open();var b=document.compatMode==_?ab:bb;u.write(b+cb);u.close()}
function A(k){function l(a){function b(){if(typeof p.readyState==db){return typeof p.body!=db&&p.body!=null}return /loaded|complete/.test(p.readyState)}
var c=b();if(c){a();return}function d(){if(!c){c=true;a();if(p.removeEventListener){p.removeEventListener(eb,d,false)}if(e){clearInterval(e)}}}
if(p.addEventListener){p.addEventListener(eb,d,false)}var e=setInterval(function(){if(b()){d()}},fb)}
function m(c){function d(a,b){a.removeChild(b)}
var e=v();var f=e.body;var g;if(navigator.userAgent.indexOf(gb)>-1&&window.JSON){var h=e.createDocumentFragment();h.appendChild(e.createTextNode(hb));for(var i=V;i<c.length;i++){var j=window.JSON.stringify(c[i]);h.appendChild(e.createTextNode(j.substring(W,j.length-W)))}h.appendChild(e.createTextNode(ib));g=e.createElement(jb);g.language=kb;g.appendChild(h);f.appendChild(g);d(f,g)}else{for(var i=V;i<c.length;i++){g=e.createElement(jb);g.language=kb;g.text=c[i];f.appendChild(g);d(f,g)}}}
noo_promisetest_PromiseTest.onScriptDownloaded=function(a){l(function(){m(a)})};r(lb,mb);var n=p.createElement(jb);n.src=k;if(noo_promisetest_PromiseTest.__errFn){n.onerror=function(){noo_promisetest_PromiseTest.__errFn(nb,new Error(ob+code))}}p.getElementsByTagName(pb)[V].appendChild(n)}
noo_promisetest_PromiseTest.__startLoadingFragment=function(a){return D(a)};noo_promisetest_PromiseTest.__installRunAsyncCode=function(a){var b=v();var c=b.body;var d=b.createElement(jb);d.language=kb;d.text=a;c.appendChild(d);c.removeChild(d)};function B(){var c={};var d;var e;var f=p.getElementsByTagName(qb);for(var g=V,h=f.length;g<h;++g){var i=f[g],j=i.getAttribute(rb),k;if(j){j=j.replace(sb,bb);if(j.indexOf(tb)>=V){continue}if(j==ub){k=i.getAttribute(vb);if(k){var l,m=k.indexOf(wb);if(m>=V){j=k.substring(V,m);l=k.substring(m+W)}else{j=k;l=bb}c[j]=l}}else if(j==xb){k=i.getAttribute(vb);if(k){try{d=eval(k)}catch(a){alert(yb+k+zb)}}}else if(j==Ab){k=i.getAttribute(vb);if(k){try{e=eval(k)}catch(a){alert(yb+k+Bb)}}}}}__gwt_getMetaProperty=function(a){var b=c[a];return b==null?null:b};s=d;noo_promisetest_PromiseTest.__errFn=e}
function C(){function e(a){var b=a.lastIndexOf(Cb);if(b==-1){b=a.length}var c=a.indexOf(Db);if(c==-1){c=a.length}var d=a.lastIndexOf(Eb,Math.min(c,b));return d>=V?a.substring(V,d+W):bb}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=p.createElement(Fb);b.src=a+Gb;a=e(b.src)}return a}
function g(){var a=__gwt_getMetaProperty(Hb);if(a!=null){return a}return bb}
function h(){var a=p.getElementsByTagName(jb);for(var b=V;b<a.length;++b){if(a[b].src.indexOf(Ib)!=-1){return e(a[b].src)}}return bb}
function i(){var a=p.getElementsByTagName(Jb);if(a.length>V){return a[a.length-W].href}return bb}
function j(){var a=p.location;return a.href==a.protocol+Kb+a.host+a.pathname+a.search+a.hash}
var k=g();if(k==bb){k=h()}if(k==bb){k=i()}if(k==bb&&j()){k=e(p.location.href)}k=f(k);return k}
function D(a){if(a.match(/^\//)){return a}if(a.match(/^[a-zA-Z]+:\/\//)){return a}return noo_promisetest_PromiseTest.__moduleBase+a}
function F(){var f=[];var g=V;function h(a,b){var c=f;for(var d=V,e=a.length-W;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
var i=[];var j=[];function k(a){var b=j[a](),c=i[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(s){s(a,d,b)}throw null}
j[Lb]=function(){{if(Mb==typeof window.setImmediate&&/{\s*\[native\scode\]\s*}/m.test(window.setImmediate.toString())){return Nb}else if(Mb==typeof window.Promise){return Ob}return Pb}};i[Lb]={'native':V,postmessage:W,promise:Qb};j[Rb]=function(){{if(Mb==typeof window.Promise){return Nb}return Sb}};i[Rb]={emulated:V,'native':W};j[Tb]=function(){var a=navigator.userAgent.toLowerCase();var b=p.documentMode;if(function(){return a.indexOf(Ub)!=-1}())return Vb;if(function(){return a.indexOf(Wb)!=-1&&(b>=Xb&&b<Yb)}())return Zb;if(function(){return a.indexOf(Wb)!=-1&&(b>=$b&&b<Yb)}())return _b;if(function(){return a.indexOf(Wb)!=-1&&(b>=ac&&b<Yb)}())return bc;if(function(){return a.indexOf(cc)!=-1||b>=Yb}())return dc;return bb};i[Tb]={gecko1_8:V,ie10:W,ie8:Qb,ie9:ec,safari:fc};__gwt_isKnownPropertyValue=function(a,b){return b in i[a]};noo_promisetest_PromiseTest.__getPropMap=function(){var a={};for(var b in i){if(i.hasOwnProperty(b)){a[b]=k(b)}}return a};noo_promisetest_PromiseTest.__computePropValue=k;o.__gwt_activeModules[S].bindings=noo_promisetest_PromiseTest.__getPropMap;r(O,gc);if(q()){return D(hc)}var l;try{h([Ob,Nb,Zb],ic);h([Nb,Nb,_b],jc);h([Pb,Sb,dc],kc);h([Ob,Nb,bc],lc);h([Nb,Sb,Zb],mc);h([Nb,Nb,bc],nc);h([Nb,Sb,dc],oc);h([Nb,Nb,dc],pc);h([Ob,Nb,dc],qc);h([Ob,Sb,_b],rc);h([Pb,Nb,Vb],sc);h([Pb,Nb,bc],tc);h([Pb,Nb,_b],uc);h([Pb,Nb,Zb],vc);h([Ob,Sb,Vb],wc);h([Ob,Nb,Vb],xc);h([Nb,Sb,_b],yc);h([Pb,Sb,Zb],zc);h([Ob,Sb,dc],Ac);h([Pb,Sb,bc],Bc);h([Pb,Sb,Vb],Cc);h([Pb,Nb,dc],Dc);h([Nb,Sb,bc],Ec);h([Nb,Nb,Zb],Fc);h([Pb,Sb,_b],Gc);h([Nb,Nb,Vb],Hc);h([Ob,Sb,Zb],Ic);h([Ob,Nb,_b],Jc);h([Nb,Sb,Vb],Kc);h([Ob,Sb,bc],Lc);l=f[k(Lb)][k(Rb)][k(Tb)];var m=l.indexOf(Mc);if(m!=-1){g=parseInt(l.substring(m+W),Xb);l=l.substring(V,m)}}catch(a){}noo_promisetest_PromiseTest.__softPermutationId=g;return D(l+Nc)}
function G(){if(!o.__gwt_stylesLoaded){o.__gwt_stylesLoaded={}}r(Oc,P);r(Oc,Pc)}
B();noo_promisetest_PromiseTest.__moduleBase=C();t[S].moduleBase=noo_promisetest_PromiseTest.__moduleBase;var H=F();if(o){var I=!!(o.location.protocol==Qc||o.location.protocol==Rc);o.__gwt_activeModules[S].canRedirect=I;function J(){var b=Sc;try{o.sessionStorage.setItem(b,b);o.sessionStorage.removeItem(b);return true}catch(a){return false}}
if(I&&J()){var K=Tc;var L=o.sessionStorage[K];if(!/^http:\/\/(localhost|127\.0\.0\.1)(:\d+)?\/.*$/.test(L)){if(L&&(window.console&&console.log)){console.log(Uc+L)}L=bb}if(L&&!o[K]){o[K]=true;o[K+Vc]=C();var M=p.createElement(jb);M.src=L;var N=p.getElementsByTagName(pb)[V];N.insertBefore(M,N.firstElementChild||N.children[V]);return false}}}G();r(O,Pc);A(H);return true}
noo_promisetest_PromiseTest.succeeded=noo_promisetest_PromiseTest();