function noo_promisetest_PromiseTest(){var O='bootstrap',P='begin',Q='gwt.codesvr.noo.promisetest.PromiseTest=',R='gwt.codesvr=',S='noo.promisetest.PromiseTest',T='startup',U='DUMMY',V=0,W=1,X='iframe',Y='javascript:""',Z='position:absolute; width:0; height:0; border:none; left: -1000px;',$=' top: -1000px;',_='CSS1Compat',ab='<!doctype html>',bb='',cb='<html><head><\/head><body><\/body><\/html>',db='undefined',eb='DOMContentLoaded',fb=50,gb='Chrome',hb='eval("',ib='");',jb='script',kb='javascript',lb='moduleStartup',mb='moduleRequested',nb='noo_promisetest_PromiseTest',ob='Failed to load ',pb='head',qb='meta',rb='name',sb='noo.promisetest.PromiseTest::',tb='::',ub='gwt:property',vb='content',wb='=',xb='gwt:onPropertyErrorFn',yb='Bad handler "',zb='" for "gwt:onPropertyErrorFn"',Ab='gwt:onLoadErrorFn',Bb='" for "gwt:onLoadErrorFn"',Cb='#',Db='?',Eb='/',Fb='img',Gb='clear.cache.gif',Hb='baseUrl',Ib='noo.promisetest.PromiseTest.nocache.js',Jb='base',Kb='//',Lb='$noo.immediate',Mb='function',Nb='native',Ob='promise',Pb='postmessage',Qb=2,Rb='$noo.promise',Sb='emulated',Tb='user.agent',Ub='webkit',Vb='safari',Wb='msie',Xb=10,Yb=11,Zb='ie10',$b=9,_b='ie9',ac=8,bc='ie8',cc='gecko',dc='gecko1_8',ec=3,fc=4,gc='selectingPermutation',hc='noo.promisetest.PromiseTest.devmode.js',ic='00A6B8FC4A20E5267152060F319A7B75',jc='15ACAEB3F9C9D48939C99836A3DC126B',kc='16238697D34173468A1047228C013138',lc='16491261F8BD9B58D575376D58412A12',mc='19704B4F45B42FA1A4106BFD7F3B4D71',nc='22E3F273F1900C758504806E79970041',oc='2572BD531902F870E20E9ECDE23293BC',pc='32881E9F61B500C54A8CFD8509AE9E70',qc='3D9BC5B9A4CA259027A28FF883D46ACD',rc='403EDA2683FD2571B9B2C521C78E471A',sc='4DDE0B39180FD6517757C1BF88D209D0',tc='502EA60E0EC5693E10FDBA03F6C3431B',uc='60B740DDD40833C597D72D41E899234D',vc='700978CC12EFDF29092F7DE893087F29',wc='77D83CAA72A47E35BAC335F29F770E15',xc='806A9DD7F9B754DCEBF93E29CA8E3ECA',yc='81080F750BC44C4AD32D5C8FD155BA1A',zc='92D97145685304BAEFC658B94CFB49EC',Ac='97709AB9354D1C94A95453433C66F096',Bc='9788C653661FCC97465E0E7E9AFAA770',Cc='AA6B045A9737A71E0F89994A45BD14A8',Dc='AA930FBE51E0A06A7D6DC760AA090585',Ec='AC3F620B3E419D6F9A238F65B2310037',Fc='AD2B0536BB07C17E84B99CF37E1CB518',Gc='B2D4DFFDED2CFC7D8BF37E7A4DA07643',Hc='B55EFEE90D81CE7E88F947FC224D62ED',Ic='C19E732F0D762027773E6D2CE9989FC0',Jc='CB404749F10AA3C7555C1880B7D2A6BB',Kc='D1DDF60315139836DD6857283548B04E',Lc='D344EB8F444C722C3410B5D9E2AA351A',Mc=':',Nc='.cache.js',Oc='loadExternalRefs',Pc='end',Qc='http:',Rc='file:',Sc='_gwt_dummy_',Tc='__gwtDevModeHook:noo.promisetest.PromiseTest',Uc='Ignoring non-whitelisted Dev Mode URL: ',Vc=':moduleBase';var o=window;var p=document;r(O,P);function q(){var a=o.location.search;return a.indexOf(Q)!=-1||a.indexOf(R)!=-1}
function r(a,b){if(o.__gwtStatsEvent){o.__gwtStatsEvent({moduleName:S,sessionId:o.__gwtStatsSessionId,subSystem:T,evtGroup:a,millis:(new Date).getTime(),type:b})}}
noo_promisetest_PromiseTest.__sendStats=r;noo_promisetest_PromiseTest.__moduleName=S;noo_promisetest_PromiseTest.__errFn=null;noo_promisetest_PromiseTest.__moduleBase=U;noo_promisetest_PromiseTest.__softPermutationId=V;noo_promisetest_PromiseTest.__computePropValue=null;noo_promisetest_PromiseTest.__getPropMap=null;noo_promisetest_PromiseTest.__installRunAsyncCode=function(){};noo_promisetest_PromiseTest.__gwtStartLoadingFragment=function(){return null};noo_promisetest_PromiseTest.__gwt_isKnownPropertyValue=function(){return false};noo_promisetest_PromiseTest.__gwt_getMetaProperty=function(){return null};var s=null;var t=o.__gwt_activeModules=o.__gwt_activeModules||{};t[S]={moduleName:S};noo_promisetest_PromiseTest.__moduleStartupDone=function(e){var f=t[S].bindings;t[S].bindings=function(){var a=f?f():{};var b=e[noo_promisetest_PromiseTest.__softPermutationId];for(var c=V;c<b.length;c++){var d=b[c];a[d[V]]=d[W]}return a}};var u;function v(){w();return u}
function w(){if(u){return}var a=p.createElement(X);a.src=Y;a.id=S;a.style.cssText=Z+$;a.tabIndex=-1;p.body.appendChild(a);u=a.contentDocument;if(!u){u=a.contentWindow.document}u.open();var b=document.compatMode==_?ab:bb;u.write(b+cb);u.close()}
function A(k){function l(a){function b(){if(typeof p.readyState==db){return typeof p.body!=db&&p.body!=null}return /loaded|complete/.test(p.readyState)}
var c=b();if(c){a();return}function d(){if(!c){c=true;a();if(p.removeEventListener){p.removeEventListener(eb,d,false)}if(e){clearInterval(e)}}}
if(p.addEventListener){p.addEventListener(eb,d,false)}var e=setInterval(function(){if(b()){d()}},fb)}
function m(c){function d(a,b){a.removeChild(b)}
var e=v();var f=e.body;var g;if(navigator.userAgent.indexOf(gb)>-1&&window.JSON){var h=e.createDocumentFragment();h.appendChild(e.createTextNode(hb));for(var i=V;i<c.length;i++){var j=window.JSON.stringify(c[i]);h.appendChild(e.createTextNode(j.substring(W,j.length-W)))}h.appendChild(e.createTextNode(ib));g=e.createElement(jb);g.language=kb;g.appendChild(h);f.appendChild(g);d(f,g)}else{for(var i=V;i<c.length;i++){g=e.createElement(jb);g.language=kb;g.text=c[i];f.appendChild(g);d(f,g)}}}
noo_promisetest_PromiseTest.onScriptDownloaded=function(a){l(function(){m(a)})};r(lb,mb);var n=p.createElement(jb);n.src=k;if(noo_promisetest_PromiseTest.__errFn){n.onerror=function(){noo_promisetest_PromiseTest.__errFn(nb,new Error(ob+code))}}p.getElementsByTagName(pb)[V].appendChild(n)}
noo_promisetest_PromiseTest.__startLoadingFragment=function(a){return D(a)};noo_promisetest_PromiseTest.__installRunAsyncCode=function(a){var b=v();var c=b.body;var d=b.createElement(jb);d.language=kb;d.text=a;c.appendChild(d);c.removeChild(d)};function B(){var c={};var d;var e;var f=p.getElementsByTagName(qb);for(var g=V,h=f.length;g<h;++g){var i=f[g],j=i.getAttribute(rb),k;if(j){j=j.replace(sb,bb);if(j.indexOf(tb)>=V){continue}if(j==ub){k=i.getAttribute(vb);if(k){var l,m=k.indexOf(wb);if(m>=V){j=k.substring(V,m);l=k.substring(m+W)}else{j=k;l=bb}c[j]=l}}else if(j==xb){k=i.getAttribute(vb);if(k){try{d=eval(k)}catch(a){alert(yb+k+zb)}}}else if(j==Ab){k=i.getAttribute(vb);if(k){try{e=eval(k)}catch(a){alert(yb+k+Bb)}}}}}__gwt_getMetaProperty=function(a){var b=c[a];return b==null?null:b};s=d;noo_promisetest_PromiseTest.__errFn=e}
function C(){function e(a){var b=a.lastIndexOf(Cb);if(b==-1){b=a.length}var c=a.indexOf(Db);if(c==-1){c=a.length}var d=a.lastIndexOf(Eb,Math.min(c,b));return d>=V?a.substring(V,d+W):bb}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=p.createElement(Fb);b.src=a+Gb;a=e(b.src)}return a}
function g(){var a=__gwt_getMetaProperty(Hb);if(a!=null){return a}return bb}
function h(){var a=p.getElementsByTagName(jb);for(var b=V;b<a.length;++b){if(a[b].src.indexOf(Ib)!=-1){return e(a[b].src)}}return bb}
function i(){var a=p.getElementsByTagName(Jb);if(a.length>V){return a[a.length-W].href}return bb}
function j(){var a=p.location;return a.href==a.protocol+Kb+a.host+a.pathname+a.search+a.hash}
var k=g();if(k==bb){k=h()}if(k==bb){k=i()}if(k==bb&&j()){k=e(p.location.href)}k=f(k);return k}
function D(a){if(a.match(/^\//)){return a}if(a.match(/^[a-zA-Z]+:\/\//)){return a}return noo_promisetest_PromiseTest.__moduleBase+a}
function F(){var f=[];var g=V;function h(a,b){var c=f;for(var d=V,e=a.length-W;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
var i=[];var j=[];function k(a){var b=j[a](),c=i[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(s){s(a,d,b)}throw null}
j[Lb]=function(){{if(Mb==typeof window.setImmediate&&/{\s*\[native\scode\]\s*}/m.test(window.setImmediate.toString())){return Nb}else if(Mb==typeof window.Promise){return Ob}return Pb}};i[Lb]={'native':V,postmessage:W,promise:Qb};j[Rb]=function(){{if(Mb==typeof window.Promise){return Nb}return Sb}};i[Rb]={emulated:V,'native':W};j[Tb]=function(){var a=navigator.userAgent.toLowerCase();var b=p.documentMode;if(function(){return a.indexOf(Ub)!=-1}())return Vb;if(function(){return a.indexOf(Wb)!=-1&&(b>=Xb&&b<Yb)}())return Zb;if(function(){return a.indexOf(Wb)!=-1&&(b>=$b&&b<Yb)}())return _b;if(function(){return a.indexOf(Wb)!=-1&&(b>=ac&&b<Yb)}())return bc;if(function(){return a.indexOf(cc)!=-1||b>=Yb}())return dc;return bb};i[Tb]={gecko1_8:V,ie10:W,ie8:Qb,ie9:ec,safari:fc};__gwt_isKnownPropertyValue=function(a,b){return b in i[a]};noo_promisetest_PromiseTest.__getPropMap=function(){var a={};for(var b in i){if(i.hasOwnProperty(b)){a[b]=k(b)}}return a};noo_promisetest_PromiseTest.__computePropValue=k;o.__gwt_activeModules[S].bindings=noo_promisetest_PromiseTest.__getPropMap;r(O,gc);if(q()){return D(hc)}var l;try{h([Pb,Nb,dc],ic);h([Ob,Sb,_b],jc);h([Ob,Sb,Zb],kc);h([Nb,Sb,dc],lc);h([Nb,Nb,_b],mc);h([Nb,Sb,_b],nc);h([Pb,Nb,Zb],oc);h([Pb,Nb,Vb],pc);h([Ob,Nb,Zb],qc);h([Pb,Sb,Vb],rc);h([Pb,Sb,bc],sc);h([Nb,Nb,dc],tc);h([Ob,Nb,dc],uc);h([Pb,Nb,bc],vc);h([Nb,Nb,bc],wc);h([Nb,Sb,bc],xc);h([Nb,Sb,Vb],yc);h([Ob,Sb,dc],zc);h([Ob,Nb,Vb],Ac);h([Nb,Nb,Zb],Bc);h([Ob,Nb,bc],Cc);h([Pb,Sb,dc],Dc);h([Ob,Sb,bc],Ec);h([Nb,Nb,Vb],Fc);h([Ob,Nb,_b],Gc);h([Pb,Sb,Zb],Hc);h([Pb,Nb,_b],Ic);h([Ob,Sb,Vb],Jc);h([Nb,Sb,Zb],Kc);h([Pb,Sb,_b],Lc);l=f[k(Lb)][k(Rb)][k(Tb)];var m=l.indexOf(Mc);if(m!=-1){g=parseInt(l.substring(m+W),Xb);l=l.substring(V,m)}}catch(a){}noo_promisetest_PromiseTest.__softPermutationId=g;return D(l+Nc)}
function G(){if(!o.__gwt_stylesLoaded){o.__gwt_stylesLoaded={}}r(Oc,P);r(Oc,Pc)}
B();noo_promisetest_PromiseTest.__moduleBase=C();t[S].moduleBase=noo_promisetest_PromiseTest.__moduleBase;var H=F();if(o){var I=!!(o.location.protocol==Qc||o.location.protocol==Rc);o.__gwt_activeModules[S].canRedirect=I;function J(){var b=Sc;try{o.sessionStorage.setItem(b,b);o.sessionStorage.removeItem(b);return true}catch(a){return false}}
if(I&&J()){var K=Tc;var L=o.sessionStorage[K];if(!/^http:\/\/(localhost|127\.0\.0\.1)(:\d+)?\/.*$/.test(L)){if(L&&(window.console&&console.log)){console.log(Uc+L)}L=bb}if(L&&!o[K]){o[K]=true;o[K+Vc]=C();var M=p.createElement(jb);M.src=L;var N=p.getElementsByTagName(pb)[V];N.insertBefore(M,N.firstElementChild||N.children[V]);return false}}}G();r(O,Pc);A(H);return true}
noo_promisetest_PromiseTest.succeeded=noo_promisetest_PromiseTest();